language: c
cache:
  directories:
    - /home/travis/.opam/
    - /home/travis/bin/opam/
before_install:
  # Install OPAM and OCaml
  - travis_retry wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s "/home/travis/bin" '4.06.1'
  - eval $(opam config env)
install:
  - opam pin add -y redtt .
script:
  - make build
  - make examples
